Mettre à jour le fichier .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,31 +3,12 @@ build-job:
   image: alpine:latest 
   script:
     - apk update
-    - apk add clang make compiler-rt ncurses-devmusl-dev
+    - apk add clang make compiler-rt ncurses-dev musl-dev
     - echo "Test du Makefile"
     - make all
-    - if [ -f "main_tui" ]; then echo "Makefile is compiling."; else echo "main_tui.o not found. " && exit 1; fi
+    - if [ -f "main_tui" ]; then echo "Makefile is compiling."; else echo "main_tui not found. " && exit 1; fi
     - make clean
-    - if [ -f "main_tui.o" ] || [-f "main_tui"]; then echo "Makefile is not cleaning well."&& exit 1; else echo "Makefile is cleaning well. "; fi
-  only:
-    - dev
-    
-
-test-job-ground:
-  stage: test
-  image: alpine:latest
-  script:
-    - apk update
-    - apk add bash make compiler-rt clang 
-    - echo "Début du test du modèle ground."
-    - OUTPUT=$(make run_test_ground 2>&1) || true # récupère sortie standard et sortie erreur
-    - if echo "$OUTPUT" | grep -q "Assertion failed\|assertion\|SIGABRT"; then
-        echo "Problème dans le modèle ground."
-        echo "$OUTPUT"
-        exit 1 # on renvoie la sortie et on sort
-      else
-        echo "Test de ground reussis !"
-      fi
+    - if [ -f "main_tui.o" ] || [ -f "main_tui" ]; then echo "Makefile is not cleaning well." && exit 1; else echo "Makefile is cleaning well."; fi
   only:
     - dev
 
@@ -60,11 +41,29 @@ test-job-obstacle:
     - echo "Début du test du modèle obstacle."
     - OUTPUT=$(make run_test_obstacle 2>&1) || true 
     - if echo "$OUTPUT" | grep -q "Assertion failed\|assertion\|SIGABRT"; then
-        echo "Problème dans le modèle obstacle."
-        echo "$OUTPUT"
-        exit 1 
+        echo "Problème dans le modèle obstacle.";
+        echo "$OUTPUT";
+        exit 1; 
       else
-        echo "Test de obstacle reussis !"
+        echo "Tests de obstacle reussis !";
+      fi
+  only:
+    - dev
+
+test-job-ground:
+  stage: test
+  image: alpine:latest
+  script:
+    - apk update
+    - apk add bash make compiler-rt clang ncurses-dev musl-dev
+    - echo "Début du test du modèle ground."
+    - OUTPUT=$(make run_test_ground 2>&1) || true # récupère sortie standard et sortie erreur
+    - if echo "$OUTPUT" | grep -q "Assertion failed\|assertion\|SIGABRT"; then
+        echo "Problème dans le modèle ground.";
+        echo "$OUTPUT";
+        exit 1; 
+      else
+        echo "Tests de grond reussis !";
       fi
   only:
     - dev
