update de la pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3,21 +3,31 @@ build-job:
   image: alpine:latest 
   script:
     - apk update
-    - apk add clang make compiler-rt ncurses-dev
+    - apk add clang make compiler-rt ncurses-devmusl-dev
     - echo "Test du Makefile"
     - make all
-    - if [ -f "main_tui.o" ]; then echo "Makefile is compiling."; else echo "main_tui.o not found. " && exit 1; fi
+    - if [ -f "main_tui" ]; then echo "Makefile is compiling."; else echo "main_tui.o not found. " && exit 1; fi
     - make clean
-    - if [ -f "main_tui.o" ]; then echo "Makefile is not cleaning well."&& exit 1; else echo "Makefile is cleaning well. "; fi
+    - if [ -f "main_tui.o" ] || [-f "main_tui"]; then echo "Makefile is not cleaning well."&& exit 1; else echo "Makefile is cleaning well. "; fi
   only:
     - dev
     
 
-test-job1:
+test-job-ground:
   stage: test
+  image: alpine:latest
   script:
-    - echo "Job exemple qui va verifier que il existe bien un fichier main_tui.c "
-    - if [ -f "main_tui.c" ]; then echo "main_tui.c exists"; else echo "main_tui.c not found" && exit 1; fi
+    - apk update
+    - apk add bash make compiler-rt clang 
+    - echo "Début du test du modèle ground."
+    - OUTPUT=$(make run_test_ground 2>&1) || true # récupère sortie standard et sortie erreur
+    - if echo "$OUTPUT" | grep -q "Assertion failed\|assertion\|SIGABRT"; then
+        echo "Problème dans le modèle ground."
+        echo "$OUTPUT"
+        exit 1 # on renvoie la sortie et on sort
+      else
+        echo "Test de ground reussis !"
+      fi
   only:
     - dev
 
@@ -37,6 +47,24 @@ test-job-player:
       else
         echo "Test échoué! La dernière ligne ne contient pas le message attendu.";
         exit 1;
+      fi
+  only:
+    - dev
+
+test-job-obstacle:
+  stage: test
+  image: alpine:latest
+  script:
+    - apk update
+    - apk add bash make compiler-rt clang 
+    - echo "Début du test du modèle obstacle."
+    - OUTPUT=$(make run_test_obstacle 2>&1) || true 
+    - if echo "$OUTPUT" | grep -q "Assertion failed\|assertion\|SIGABRT"; then
+        echo "Problème dans le modèle obstacle."
+        echo "$OUTPUT"
+        exit 1 
+      else
+        echo "Test de obstacle reussis !"
       fi
   only:
     - dev
